title: Let's Cook!
description: A personal blog hosted on GitHub Pages
url: https://lrshls.github.io/Making-Meth/
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
