title: Let's Cook!
description: A personal blog hosted on GitHub Pages
url: https://username.github.io
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
markdown: kramdown
exclude:
 - Gemfile
 - Gemfile.lock
