# Homepage Configuration Example
title: "My Dashboard"
theme: "dark"  # Options: light, dark, custom

# Navigation Links
navigation:
  - name: "Home"
    url: "/"
    icon: "mdi-home"
  - name: "Email"
    url: "https://mail.example.com"
    icon: "mdi-email"
  - name: "Calendar"
    url: "https://calendar.example.com"
    icon: "mdi-calendar"



